### ISSUE TITLE
First weekday sunday :(

### ISSUE THREAD

**Issue by pefman** [ianperrin/MMM-Strava#19]
Hey!

Thanks for an awesome addon!
Could you please make it possible to choose the start of the week.
It appears to be stuck on Sunday 👎

**Comment by ianperrin** [comment]
Hi @pefman - I've just pushed a change documenting the `locale` option. If you update to the latest version and add `locale: "en-gb"` (or similar) in the module config the day of the week will change accordingly

**Comment by pefman** [comment]
Thats awesome, keep up the good work!
