### ISSUE TITLE
The stats displayed in the table should be configurable via options

### ISSUE THREAD

**Issue by ianperrin** [ianperrin/MMM-Strava#3]
Athlete stats and totals includes more data points than simply count, distance and achievements.

Use config options to specific which stats should be displayed

**Comment by dmarkscouk** [comment]
I've tried 20 variations, but don't seem to be able to get ride of the swim activity. I'm using:

`activities: "["ride", "run"]",`

Thanks, David.

**Comment by ianperrin** [comment]
Hi David

It looks like you've got a few too many quotation marks in there. Try this
````
		{
			module: 'MMM-Strava',
			position: 'top_right', 
			header: 'Strava Swim Activity',
			config: {
				activities: ['swim'],
				mode: 'table',
				strava_id: 'YOUR_STRAVA_ID',
				access_token: 'YOUR_ACCESS_TOKEN',
			}
		},
````

**Comment by dmarkscouk** [comment]
Hi Ian,

Thanks for such a quick response. I'll try this when I get home.

Thanks, David.

**Comment by dmarkscouk** [comment]
Yes this has worked. Thanks :)
