### ISSUE TITLE
Module not aggregating virtual activities - fix

### ISSUE THREAD

**Issue by coolbikerdad** [ianperrin/MMM-Strava#31]
When submitting a new issue, please supply the following information:

Platform (Hardware/OS): Raspberry Pi, Raspbian Buster

Node Version: latest

MagicMirror Version: latest

Description: The way that virtual activities are aggregated (by adding e.g. virtualride to ride activity types) does not work correctly. The technique is to lower case each activity type and replace any ‘virtual’ substring with nothing. However, the call used,  ....replace(‘virtual’), omits a replacement string which now defaults to ‘undefined’ so the activity name becomes ‘undefinedride’ and is not summed with ‘ride’ activities. Fix is to amend the replace call with ...replace(“virtual”,””)

**Comment by ianperrin** [comment]
Thanks @coolbikerdad - looks like that bug was added in an earlier commit - c2046c6 - should be fixed now
