### ISSUE TITLE
I don't understand wich information to write in fields to setting api

### ISSUE THREAD

**Issue by tet102** [ianperrin/MMM-Strava#35]
Hello,
Can you help me please to write informations in fields 
see screen capture below...
Thanks

![Capture](https://user-images.githubusercontent.com/33205971/68701848-ec376a80-0587-11ea-9833-043582b19d70.JPG)

**Comment by ianperrin** [comment]
Hi @tet102 

The important value is the “Domaine du rappel pour l’autorisation” (or Authorisation Callback Domain). 

Set this to the IP address or domain name you use to access the MagicMirror. So if you use http://localhost:8080, enter `localhost` , if you use http://192.168.0.21:8080, enter `192.168.0.21`

Perhaps this screenshot helps

![Strava API Settings](https://raw.githubusercontent.com/ianperrin/MMM-Strava/master/.github/Strava-API-Application-Settings.png)

**Comment by tet102** [comment]
Hello ianperrin  its perfect you are very cool...Thank you... Thank you
