### ISSUE TITLE
How do I change the display type from table to chart?

### ISSUE THREAD

**Issue by daymo87** [ianperrin/MMM-Strava#40]
Hi Ian

Really like the Strava feature im just struggling to change the display type from table to chart any advise for a newbie?

Thanks

Damon

When submitting a new issue, please supply the following information:

Platform (Hardware/OS):

Node Version:

MagicMirror Version:

Description: Provide a detailed description about the issue and include specific details to help us understand the problem. Adding screenshots will help describing the problem.

Steps to Reproduce: List the step by step process to reproduce the issue.

Expected Results: Describe what you expected to see.

Actual Results: Describe what you actually saw.

Configuration: What does the used config.js file look like? Don't forget to remove any sensitive information!

Additional Notes: Provide any other relevant notes not previously mentioned. This is optional.

**Comment by elustig115** [comment]
I am having a similar issue. The normal table shows up, and has information in it. But the bar chart is blank!

**Comment by ianperrin** [comment]
Hi @daymo87 - did you solve your issue? If not can you post more details and perhaps a copy of your config (masking the api details)

**Comment by daymo87** [comment]
Hi mateYeah I manged to get it sorted by adding units to main config & setting at imperial now it displays how i wantedThanks DamonSent from my Samsung Galaxy smartphone.
-------- Original message --------From: Ian <notifications@github.com> Date: 21/07/2020  22:41  (GMT+00:00) To: ianperrin/MMM-Strava <MMM-Strava@noreply.github.com> Cc: daymo87 <damonlock@me.com>, Mention <mention@noreply.github.com> Subject: Re: [ianperrin/MMM-Strava] Changing display type  (#40) 
Hi @daymo87 - did you solve your issue? If not can you post more details and perhaps a copy of your config (masking the api details)
