### ISSUE TITLE
Authentication Issue

### ISSUE THREAD

**Issue by Raven4150** [ianperrin/MMM-Strava#43]
Hi 
I have an issue with the authentication. I have created a Strava API, Get the Client ID and the Client Secret, That is all done but still it doesn't work. I think it has something to do with the webadress, but I don't know which one I should use. Please I need your help.
Cheers

**Comment by Raven4150** [comment]
Solved it.

**Comment by bachoo786** [comment]
Hey @Raven4150  how did you solve it? I have the same issue. Thanks

**Comment by Raven4150** [comment]
Honestly I didn't. I didn't find any possible solution

**Comment by ianperrin** [comment]
@Raven4150 - sorry to hear you didn’t solve the problem, are you able to provide more information about what you have done, and where you are having issues?

@bachoo786 - perhaps you you start a new issue and describe you problem in detail and I can try to assist?

**Comment by CharonBeber** [comment]
Hi @ianperrin,
first of all, this is definatelly one of the best apps for magic mirror. Thx a lot for that!
After my old mirror wend to smoke, i had to rebuild a new one. I freshly set up a complete new os and MM. First installation vnc server, second MMM-Strava. You made a great explanation on what to write on the strava api auth website.
But the ip adress 192.168.178.22 of the pi, eather the one of my laptop 192.168.178.33. I´m remoting from, eather 127.0.0.0 or 127.0.0.1 or localhost are working. I feal really dumb. Where didn´t i get the point?
Do i have to add the :8080? The old settings on the webpage had 127.0.0.0 but this is not working anymore...
