### ISSUE TITLE
Chart only includes the first 200 activities for the chosen period

### ISSUE THREAD

**Issue by mattisson963** [ianperrin/MMM-Strava#46]
When submitting a new issue, please supply the following information:

Platform (Hardware/OS): Virtual VMware machine, Ubuntu1804

Node Version: 
![Skärmklipp](https://user-images.githubusercontent.com/69696372/90290623-7cd80980-de7e-11ea-98b4-1902bd3b32fc.JPG)
![screen](https://user-images.githubusercontent.com/69696372/90290723-ab55e480-de7e-11ea-9f7b-affd36a2c23a.jpg)

MagicMirror Version:2.10.1

Description: I don´t get stats from July and august. There have been som API changes in late June, does this version support them? I have attached a jpg, there are a lot of stats from july but they are not shown.

Configuration: 
```
{
      module: "MMM-Strava",
        position: "top_left",
	header: 'Strava cykling 2020',
        config: {
		client_id: "xxxx",
client_secret: "xxxx",
mode: "chart",
		period: "ytd",            
	activities: ["ride"],
	reloadInterval: "3600000",
updateInterval: "3600000",
        },
    },
```

Additional Notes: Provide any other relevant notes not previously mentioned. This is optional.

**Comment by mattisson963** [comment]
Weekly(Recent) chart works but not yearly.

**Comment by ianperrin** [comment]
@mattisson963 are you still experiencing problems with the module?

**Comment by mattisson963** [comment]
@ianperrin 
No. It doesn't worked the whole 2020 but started to work 1 jan 2021 without any changes from me. Don't know why, it may have been something that I got paid user to Strava during that time last summer. Thanks for the replay.

**Comment by ianperrin** [comment]
Hi @mattisson963 - quick question, how many activities have you recorded in 2020?

 I've noticed Strava place a limit on the number of activities returned by the api in each call, so my current theory is that when requesting your "year to date" activities for 2020, the limit was exceeded. This would also explain why it started working again in Jan 2021 as only 1 months data was required.

If you're able to let me know, that would be great as I can then look into this bug and handle it within the module...

**Comment by mattisson963** [comment]
Hi @ianperrin
That may be the reason. I use my bike to work so I had 438 activities 2020, so probably around 200 activities when it stoped to work. So that is a limit Strava has and nothing to do about?
Regards Thomas

**Comment by ianperrin** [comment]
@mattisson963 thanks for the update. There’s a limit to how many activities are returned by the API. It’s possible to work around, but just needs a little time and focus from me. I’ll add it to the list. 😉
