### ISSUE TITLE
Support the display of other activity types

### ISSUE THREAD

**Issue by MxRtr** [ianperrin/MMM-Strava#48]
Hi, is it possible to integrate the option to display other activities than swim, bike, run? E.g. Crossfit, hiking, etc.

**Comment by ianperrin** [comment]
@MxRtr - Working on it ;) 

Can I ask, do you use `chart` or `table` mode?

**Comment by MxRtr** [comment]
@ianperrin Thank you very much for implementing this feature. 

Currently I'm using chart mode, but do not prefer one. So I will switch to table mode.

**Comment by ianperrin** [comment]
Great, and hope it works for you. I close this issue now. If you encounter any problems, please open a new issue.
