### ISSUE TITLE
Trouble Authenticating

### ISSUE THREAD

**Issue by ndm5** [ianperrin/MMM-Strava#49]
Hi,

I've not quite got the module working yet, I'm quite new to this. I've followed the installation steps down to step 5, but I can't seem to authenticate the module. My Strava account is linked to my Google account and when I try to log in, I get a message saying the web browser isn't supported. Am I doing something wrong?

**Comment by ianperrin** [comment]
@ndm5 - did you solve the problem? If not can you let me know 
* how you are accessing the MagicMirror whilst authenticating? e.g. on a screen attached to the pi or from another computer
* what value you entered for the Authorisation Callback Domain in the Strava API Application settings
thanks

**Comment by ianperrin** [comment]
I hope you were able to resolve your issue with the authentication.

I am going to close the issue, but if you are still experiencing the error, please do re-open it and provide as much information as possible. Thanks
