### ISSUE TITLE
Chart mode displaying wrong time and not refreshing.

### ISSUE THREAD

**Issue by Papi77** [ianperrin/MMM-Strava#9]
Hi,
The time displayed under the distance (e.g. for Running) is incorrect.
On Monday I have run for 43 minutes (screenshot from Strava portal):
![strava screenshot](https://cloud.githubusercontent.com/assets/26800136/25017130/e564b272-2082-11e7-948a-420a624df6fb.PNG)
 
 
 
 
However, the MagicMirror screen shows **1h**43min:

![magicmirror screenshot](https://cloud.githubusercontent.com/assets/26800136/25017027/7f908c96-2082-11e7-94cd-d9425f61ab96.PNG)

Looks like it adds an extra hour on the first entry! :)
When second entry was added - the total time is calculated correctly.

**Comment by fuchsde** [comment]
Hey Papi77,
go to the folder MagicMirror/modules/MMM-Strava in your MagicMirror project. Open the "MMM-Strava.js" and search for the line containing "durationListItem.innerHTML". Replace this line with the following code:
if(this.roundedToFixed(movingTime.asHours(), 1) > 1.0)
{
	durationListItem.innerHTML = this.roundedToFixed(movingTime.asHours(), 0) + "h " + this.roundedToFixed(movingTime.minutes(), 0) + "m";
}
else	
{
	durationListItem.innerHTML = "0h " + this.roundedToFixed(movingTime.minutes(), 0) + "m";
}

Best regards, 
fuchsde

**Comment by ianperrin** [comment]
Looks good @fuchsde do you want to submit a pull request?
